### ISSUE TITLE
Index script chokes on CSS file with utf-8 error

### ISSUE THREAD

**Issue by nickwynja** [infor-design/website#631]
**Describe the bug**

**To Reproduce**
1. Run `make index_s3`
2. Index will run fine until it hits `docs/ids-pendo/1.0.0/assets/dist/global.min.css` where it fails with error:
```
Traceback (most recent call last):
  File "/home/app/index_s3.py", line 113, in <module>
    s3_sync(**kwargs)
  File "/home/app/index_s3.py", line 39, in s3_sync
    read_contents_str = read_contents_bytes.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```
**Expected behavior**
Script either skips CSS and JS files, or can properly decode.

**Comment by corpulent** [comment]
@nickwynja this push https://github.com/infor-design/website/commit/44610c8ab96f65a103843429208e0d376592edc2 fixes this.
